server:
  port: 9004
spring:
  profiles:
    active: mongodb
  application:
    name: music-details
eureka:
  client:
    service-url:
      defaultZone: http://139.224.66.83:8761/eureka
  instance:
    prefer-ip-address: true
#    ip-address: 139.224.66.83