music:
  song:
    nginx:
      server: http://139.224.66.83:8888
spring:
  application:
    name: music_song
  profiles:
    active: mongodb
server:
  port: 9000 # song
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://139.224.66.83:8761/eureka
