music:
  playlist:
    nginx:
      server: http://138.224.66.83:8888
spring:
  application:
    name: music-playlist
  profiles:
    active: mongodb
server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 139.224.66.93
  client:
    service-url:
      defaultZone: http://139.224.66.83:8761/eureka