server:
  port: 4006
spring:
  application:
    name: music-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # 定义 search
        - id: search
          uri: lb://music-search
          predicates:
            - Path=/search
        # 定义song 路由
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/next
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/favorites
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/previous
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 139.224.66.83
  client:
    service-url:
      defaultZone: http://139.224.66.83:8761/eureka

