server:
  port: 4006
spring:
  application:
    name: music-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # 定义 playlist
        - id: playlist
          uri: lb://music-playlist
          predicates:
            - Path=/pl/cat
        - id: playlist
          uri: lb://music-playlist
          predicates:
            - Path=/pl/default
        # 定义 search
        - id: search
          uri: lb://music-search
          predicates:
            - Path=/search
        # 定义song 路由
        - id: collect
          uri: lb://music-song
          predicates:
            - Path=/collect/exists
        - id: collect
          uri: lb://music-song
          predicates:
            - Path=/collect/t
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/next
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/previous
        - id: song
          uri: lb://music-song
          predicates:
            - Path=/song/favorites
        - id: tag
          uri: lb://music-song
          predicates:
            - Path=/tag/
        - id: tag
          uri: lb://music-song
          predicates:
            - Path=/tag/random
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 139.224.66.83
  client:
    service-url:
      defaultZone: http://139.224.66.83:8761/eureka

