spring:
  data:
    mongodb:
#      host: 139.224.66.83
#      port: 27017
#      username: PJMVSSM
#      password: 123456
#      authentication-database: admin
#      database: nobody
      uri: mongodb://PJMVSSM:123456@139.224.66.83:27017/nobody