server:
  port: 8761
spring:
  application:
    name: music-eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 139.224.66.83
    prefer-ip-address: true # 注册服务的时候优先选择IP，不是主机名